spring.application.name=persistence-service
server.port=8081

spring.datasource.url=jdbc:h2:file:./data/collabdb;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.hikari.data-source-properties.TimeZone=UTC
jakarta.persistence.jdbc.url=jdbc:h2:mem:collabdb
jakarta.persistence.jdbc.user=sa
jakarta.persistence.jdbc.password=
jakarta.persistence.jdbc.driver=org.h2.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.acks=1
spring.kafka.consumer.properties.isolation.level=read_committed
